### ISSUE TITLE
Cant' use sass variables in component scss

### ISSUE THREAD

**Issue by vishnunarayanan** [spkellydev/nextjs-scss-ssr-react-tutorial#1]
I have modified background-color in changed the Navbar.scss as shown

mark {
  border-radius: 10px;
  background-color: **$green;**
  display: flex;
  flex-direction: column-reverse;
}

and getting

Error in ./Navbar.scss
Module build failed: ModuleBuildError: Module build failed: 
  background-color: $green;
                   ^
      Undefined variable: "$green".

**Comment by spkellydev** [comment]
You would need to pull in your vars to that specific file, as it is not a part of the global stylesheet.
